# Dependencies
markdown:         rdiscount
pygments:         true

# Server
destination:    ./_site
exclude:      [".gitignore", "bower.json", "composer.json", "Gruntfile.js", "package.json", "node_modules", "bower_components", "src", "releases", "README.md", "install", "tests"]
include:      ["_assets","_pages"]
port:       9001

# App
app:        "Stan Plugins"
version:      "0.0.19"

# Formatting
tab:          "&nbsp;&nbsp;"

# URLs
download:     "http://stan-utils.smartarts.co.uk/releases/[version]/stan-plugins-[version].zip"
github:       "https://github.com/awomersley/stan-plugins"
